name: Get latest version tag
author: 'Andrew McLachlan'
description: 'Get the latest version tag from the git repository and extract the major and minor version numbers'
runs:
  using: "composite"
  steps:
    - shell: bash
      id: get-version
      run: |
        TAG=$(git describe --tags --match "v[0-9]*.[0-9]*" --abbrev=0 2>/dev/null || echo "v0.1")
        echo "Latest tag: $TAG"
        MAJOR=$(echo "$TAG" | cut -d. -f1 | cut -c2-)
        MINOR=$(echo "$TAG" | cut -d. -f2)
        echo "major=$MAJOR" >> $GITHUB_OUTPUT
        echo "minor=$MINOR" >> $GITHUB_OUTPUT
outputs: 
  version:
    description: 'The version number'
    value: ${{ steps.get-version.outputs.major }}.${{ steps.get-version.outputs.minor }}