name: 'Get Major and Minor version numbers from MSBuild props'
author: 'Andrew McLachlan'
description: 'Get the major and minor number from a given file'
inputs:
  project:
    description: 'Path to the project containing the version number'
    required: false
    default: 'Directory.Build.props'
  version-property-name:
    description: 'Name of the MSBuild property containing the version number'
    default: 'Version'
    required: false
runs:
  using: composite
  steps:
    - shell: pwsh
      id: get-version
      run: ${{ github.action_path }}/GetVersion.ps1 -Project ${{ inputs.project }} -VersionPropertyName ${{ inputs.version-property-name }}
outputs:
  major:
    description: 'The major version number'
    value: ${{ steps.get-version.outputs.major }}
  minor:
    description: 'The minor version number'
    value: ${{ steps.get-version.outputs.minor }}
  patch:
    description: 'The patch version number'
    value: ${{ steps.get-version.outputs.patch }}
