name: 'Set Version Number'
author: 'Andrew McLachlan'
description: 'Get the version number from a given file and set the build portion to the run number'
inputs:
  filePath:
    description: 'Path to the file containing the version number'
    required: true
  versionPropertyName:
    description: 'Name of the XML property containing the version number'
    required: true
runs:
  using: composite
  steps:
    - shell: pwsh
      id: get-version
      run: ${{ github.action_path }}\GetVersion.ps1 -FilePath ${{ inputs.filePath }} -VersionPropertyName ${{ inputs.versionPropertyName }}
outputs:
  version:
    description: 'The version number'
    value: ${{ steps.getversion.outputs.version }}
