name: Swap Slot
on:
  workflow_call:
    inputs:
        environment:
          description: 'Environment to deploy to'
          type: string
          required: true
        app-name:
          description: 'Azure Web App name'
          type: string
          required: true
        slot-name:
          description: 'Azure Web App deployment slot name'
          type: string
          required: true
        resource-group:
          description: 'Azure resource group name'
          type: string
          required: true
    secrets:
      AZURE_CLIENT_ID:
        description: 'Azure client ID'
        required: true
      AZURE_TENANT_ID:
        description: 'Azure tenant ID'
        required: true
      AZURE_SUBSCRIPTION_ID:
        description: 'Azure subscription ID'
        required: true

permissions:
  id-token: write

jobs:
  swap-slot:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Swap slots"
        run: az webapp deployment slot swap -s ${{ inputs.slot-name }} -n ${{ inputs.app-name }} -g ${{ inputs.resource-group }}

      - name: logout
        run: |
          az logout
